version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
       
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/data:/var/lib/grafana 
    ports:
      - 5000:5000
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
      - GF_SERVER_HTTP_PORT=5000
    links:
      - prometheus

  customer_tracking:
    build: 
       context: ./
    image: customer_tracking_image     
    ports:
       - 8080:8080
    environment:
      DISPLAY: $DISPLAY
    volumes:
       - /dev:/dev
       - /tmp/.X11-unix:/tmp/.X11-unix 
       - ./streams:/workspace/streams
       
    privileged: true

    command: ./customer_tracking.sh ./streams/hiv00004.mp4

